INSERT INTO users (email, password, first_name, last_name, phone_number, address, zip_code, role, creation_date) VALUES ('fog_admin@gmail.com', 'fog_admin', 'Admin', 'Fog', 12345678, 'Fog Admin 34', 3456, 2, CURDATE());
INSERT INTO users (email, password, first_name, last_name, phone_number, address, zip_code, role, creation_date) VALUES ('customer@gmail.com', 'customer', 'First', 'Customer', 12345678, 'Customer 34', 5555, 0, CURDATE());
INSERT INTO users (email, password, first_name, last_name, phone_number, address, zip_code, role, creation_date) VALUES ('customer2@gmail.com', 'customer2', 'Second', 'Customer', 23335577, 'Customer 22', 6666, 0, CURDATE());
insert into users (email, password, first_name, last_name, phone_number, address, zip_code, role, creation_date) VALUES ('andrian@fog.dk','69696969','Andrian','Vangelov',77733399,'@home123', 2200, 1, CURDATE());
insert into users (email, password, first_name, last_name, phone_number, address, zip_code, role, creation_date) VALUES ('patrick@fog.dk','69696969','Patrick','Fenger',11188555,'@home456', 2100, 1, CURDATE());
insert into users (email, password, first_name, last_name, phone_number, address, zip_code, role, creation_date) VALUES ('petru@fog.dk','69696969','Petru','Catana',00077999,'@home789', 2300, 1, CURDATE());
insert into users (email, password, first_name, last_name, phone_number, address, zip_code, role, creation_date) VALUES ('alexandar@fog.dk','69696969','Alexandar','Osenov',66699000,'@home101', 3460, 1, CURDATE());
insert into products (price, height, width, length, has_shed, rooftop_type, name) VALUES (3495.0, 2.5, 2.5, 6.5, 0, 0, 'CAR01');
insert into products (price, height, width, length, has_shed, rooftop_type, shed_length, shed_width, name) VALUES (7995.0, 3.3, 2.6, 7.3, 1, 0, 2.0, 2.0, 'CAR02');
insert into products (price, height, width, length, has_shed, rooftop_type, rooftop_angle, name) VALUES (12995.0, 4.3, 2.7, 5.3, 0, 1, 30, 'CAR03');
insert into products (price, height, width, length, has_shed, rooftop_type, shed_length, shed_width, rooftop_angle, name) VALUES (18995.0, 5.3, 2.8, 8.3, 1, 1, 1.5, 1.5, 25, 'CAR04');
INSERT into orders (price, creation_date, customer_id, order_status) VALUES (3495.0,CURDATE(), 2, 0);
INSERT into orders (price, creation_date, customer_id, order_status) VALUES (7995.0,CURDATE(), 2, 0);
INSERT into orders (price, creation_date, customer_id, order_status) VALUES (12995.0,CURDATE(), 3, 0);
INSERT into orders (price, creation_date, customer_id, order_status) VALUES (18995.0,CURDATE(), 3, 0);
insert into order_details (order_id, product_id) VALUES (1,1);
insert into order_details (order_id, product_id) VALUES (2,2);
insert into order_details (order_id, product_id) VALUES (3,3);
insert into order_details (order_id, product_id) VALUES (4,4);
insert into delivery (delivery_date, delivery_status, order_id, price) VALUES ('2017-05-05', 0, 1, 250.0);
insert into delivery (delivery_date, delivery_status, order_id, price) VALUES ('2017-05-15', 0, 2, 1475.0);
insert into delivery (delivery_date, delivery_status, order_id, price) VALUES ('2017-05-25', 1, 3, 1875.0);
insert into delivery (delivery_date, delivery_status, order_id, price) VALUES ('2017-06-30', 2, 4, 250.0);
insert into invoice (product_id, customer_id, sales_rep_id, creation_date, total_price) VALUES (1, 2, 4, '2017-05-06', 3700.0);
insert into invoice (product_id, customer_id, sales_rep_id, creation_date, total_price) VALUES (1, 2, 5, '2017-05-06', 8500.0);
insert into invoice (product_id, customer_id, sales_rep_id, creation_date, total_price) VALUES (1, 3, 6, '2017-05-06', 15000.0);
insert into invoice (product_id, customer_id, sales_rep_id, creation_date, total_price) VALUES (1, 3, 7, '2017-05-06', 19300.0);
UPDATE order_details SET sales_rep_id = 4, delivery_id =1, invoice_id = 1 WHERE order_id = 1;
UPDATE order_details SET sales_rep_id = 5, delivery_id =2, invoice_id = 2 WHERE order_id = 2;
UPDATE order_details SET sales_rep_id = 6, delivery_id =3, invoice_id = 3 WHERE order_id = 3;
UPDATE order_details SET sales_rep_id = 7, delivery_id =4, invoice_id = 4 WHERE order_id = 4;

